blocks/collapse/collapse.css
blocks/collapse/collapse.js
styles/styles.css

Fix #4
Test URLs:
- After: https://issues4--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Implement Drawers (#4)

---

blocks/columns/columns.css
blocks/columns/columns.js

See #9
Test URLs:
- After: https://issues9--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Implement basic image dl columns (#9)

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js

Only the basic structure is in place (but navigation buttons should work as well as indicators) - need styling.
See #8 
Test URLs:
- After: https://issue8--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Basic implementation for the carousel (no styling) (#8)

---

blocks/header/header.js
blocks/navigation/navigation.css
blocks/navigation/navigation.js
scripts/lib-franklin.js
styles/styles.css

https://github.com/hlxsites/zeiss/issues/7
Test URLs:
- After: https://navigation--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

add navigation block

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js
styles/images.css
styles/lazy-styles.css

https://github.com/hlxsites/zeiss/issues/8
Test URLs:
- After: https://carousel--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

support carousel block

---

blocks/collapse/collapse.css
blocks/collapse/collapse.js
styles/icons.css
styles/lazy-styles.css
styles/styles.css

https://github.com/hlxsites/zeiss/issues/4
Test URLs:
- After: https://collapse--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

support collapse block

---

blocks/contact/contact.js
blocks/hero/hero.css
blocks/hero/hero.js
scripts/scripts.js

Fix #5 
Test URLs:
- After: https://issue5--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Implement hero autoblocking and hero block

---

blocks/footer/footer.css
blocks/footer/footer.js

https://github.com/hlxsites/zeiss/issues/2
Test URLs:
- After: https://footer--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

add footer block

---

blocks/hero/hero.js
blocks/social/social.css
blocks/social/social.js
scripts/utils.js
styles/styles.css

https://github.com/hlxsites/zeiss/issues/10
Test URLs:
- After: https://social--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

add social block

---

blocks/header/header.css
blocks/header/header.js
blocks/navigation/navigation.css
styles/styles.css

https://github.com/hlxsites/zeiss/issues/1
Test URLs:
- After: https://megamenu--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

add header megamenu support (desktop)

---

blocks/article-list/article-list.css
blocks/article-list/article-list.js

See #11 
Test URLs:
- After: https://issue11--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Add an article block (only hardcoded content for now)

---

blocks/article-list/article-list.js

- feat(article-list): fetch articles from query index
- feat(article-list): limit the number of articles according to block config
After: https://dynamic-article-feed--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet
Needed for #31

Generate Article List from Index

---

tools/importer/import.js

Fix #56
URL for testing:
- https://issue-56--zeiss--hlxsites.hlx.page/

Import text-media-grid as cards

---

tools/importer/import.js

Improved error handling and importing 'contact' block

Improved error handling and importing 'contact' block

---

blocks/hero/hero.js
scripts/scripts.js

Fix #55 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/drafts/satyam/spie-award-imported
- After: https://issue-55--zeiss--hlxsites.hlx.page/drafts/satyam/spie-award-imported

Removed social markup from hero block and also added a fix on text block

---

helix-query.yaml

Fix #50
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award
- After: https://tags--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award

Added tags to index definition

---

blocks/collapse/collapse.css
blocks/collapse/collapse.js
styles/styles.css
styles/zeiss-styles.css

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/drafts/alina/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet
- After: https://generic-link--zeiss--hlxsites.hlx.page/drafts/alina/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

generic link

---

blocks/hero/hero.js
styles/simplified-styles.css

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-spendet-25000-euro-an-kinderstiftung-knalltuete
- After: https://hero-font-fixes--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-spendet-25000-euro-an-kinderstiftung-knalltuete

Fixes in hero font styling

---

en/placeholders.json
scripts/lib-franklin.js

Fix #83 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/drafts/tmaret/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award
- After: https://issue-83-no-placeholder--zeiss--hlxsites.hlx.page/drafts/tmaret/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award

Remove en/placeholders.json and fix the franklin library

---

blocks/hero/hero.js
scripts/delayed.js
scripts/utils.js
tools/importer/import.js

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/zeiss-expandiert-am-forschungs-und-entwicklungsstandort-rossdorf
- After: https://new-articles--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/zeiss-expandiert-am-forschungs-und-entwicklungsstandort-rossdorf

Add new articles and other miscellaneous fixes

---

blocks/hero/hero.js
scripts/utils.js
styles/simplified-styles.css
test/blocks/hero/hero.plain.html
test/blocks/hero/hero.test.js
test/resources/de/placeholders.json
test/resources/en/placeholders.json
test/scripts/head.html
test/scripts/utils.test.js
test/test-utlis.js

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/2023/zeiss-expands-at-the-rossdorf-research-and-development-site
- After: https://date-locale--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/2023/zeiss-expands-at-the-rossdorf-research-and-development-site
Before
After

Localize date

---

styles/simplified-styles.css

Fixes: #103
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/2023/new-multifunctional-factory-in-wetzlar
- After: https://issue-103--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/2023/new-multifunctional-factory-in-wetzlar

Support bulleted lists

---

scripts/delayed.js
scripts/utils.js
test/scripts/delayed.test.js
test/scripts/utils.test.js

Fix #116 
Test URLs:
- After: https://issue-116--zeiss--hlxsites.hlx.page/

Use different GTM container for preview/live

---

scripts/delayed.js
scripts/scripts.js

Fix #104
Test URLs:
- After: https://issue-104-4--zeiss--hlxsites.hlx.page/

Increase delayed execution to 6s

---

blocks/columns-new/columns-new.css
blocks/columns-new/columns-new.js
styles/simplified-styles.css

Fix #81 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/drafts/piyush/intels-preferred-quality-supplier-award-2020
- After: https://issue-81--zeiss--hlxsites.hlx.page/drafts/piyush/intels-preferred-quality-supplier-award-2020

Issue-81 Changes added for columns-new

---

blocks/collapse/collapse.css

Test URLs:
- After: https://issue-11--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

issue-11 - fix styling for collapsible

---

blocks/contact/contact.js
tools/importer/import.js

Fix #133 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award
- After: https://missing-authors--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award

Added missing authors

---

tools/importer/import.js

Fix #136 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/intels-2022-epic-distinguished-supplier-award-en-only
- After: https://issue-136--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/intels-2022-epic-distinguished-supplier-award-en-only

Issue-136 Columns New Block changes added in import.js

---

blocks/contact/contact.js

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020
- After: https://issue-126-9--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020

Issue-126-9 Space increased for contact section

---

blocks/columns/columns.js

* Populate headline (head and sub)
* Populate nb of pages
* Translate template
Fix #140
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/
- After: https://issue-140--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Fix press photo section

---

blocks/header/header.css
blocks/header/header.js
scripts/lib-franklin.js
styles/styles.css

Fix #45 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award
- After: https://nav--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/spie-award
*Note:* Acouple of things pending here with second level drill drown and back button support which I'll take up seperately.

feat: Fetch nav bar

---

blocks/columns-new/columns-new.css

Fix #131 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss
- After: https://issue-131--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss

Issue-131 Columns new css changed

---

blocks/footer/footer.css
styles/simplified-styles.css

Fix #146 
Test URLs:
- Before:  https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss
- After:  https://issue-146--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss

issue-146 Bottommost dark footer Size changed

---

styles/simplified-styles.css

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/2023/new-multifunctional-factory-in-wetzlar
- After:  Before: https://issue-10--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/2023/new-multifunctional-factory-in-wetzlar

issue-10 - smaller space between headline and text

---

blocks/article-list/article-list.js

Fix #160
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/quality-supplier-award-2019
- After: https://issue-160--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/quality-supplier-award-2019

Article list block not localised

---

blocks/text-media/text-media.css

Fixes #157
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt
- After: https://issue-157--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt

Fix image width for text-media blocks

---

blocks/footer/footer.js

Fix #173
Test URLs:
- After: https://issue-173--zeiss--hlxsites.hlx.page/

Localise footer with placeholder

---

blocks/columns-new/columns-new.css
blocks/columns-new/columns-new.js
test/blocks/columns-new/columns-new.plain.html
test/blocks/columns-new/columns-new.test.js

Fix #154
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss
- After: https://issue-154--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss

issue-154 Copyright below image handled

---

test/blocks/columns-new/columns-new.test.js

Fix #154 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss
- After: https://issue-154-temp--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss

issue-154 Extra Test case added For Copyright

---

styles/styles.css

Fix #178 
Test URLs:
- After: https://issue-178--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Issue-178 Incorrectly styled copyright text changed

---

blocks/header/header.css
styles/styles.css

Fix #182 
Test URLs:
- After: https://issue-182--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Issue-182 Header CSS Changes

---

blocks/columns/columns.js

Fix #179
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/quality-supplier-award-2019
- After: https://issue-179--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/quality-supplier-award-2019

Localise column block

---

blocks/footer/footer.css

Fix #153 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020
- After: https://issue-153--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020

issue-153 Css changed for footer language big screen

---

tools/importer/import.js

Fix #186
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet
- After: https://issue-186--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

Use absolute url for `further information` link in the collapse block

---

blocks/columns-new/columns-new.css
styles/simplified-styles.css

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020
- After: https://issue-22--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020

issue-22 - Links not properly styled

---

tools/download-content-markdown.mjs

Fix #166
Test URLs:
- After: https://issue-166--zeiss--hlxsites.hlx.page/

Add tool to download a md version of the site

---

tools/importer/import.js

A text-media block is one of these:
* a text-media block in the original document
* a carousel with 1 image
Fix #190
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020
- After: https://issue-190--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020

Handle text-media in import.js

---

tools/importer/import.js

* Ensure J. Rapp is included to every article
* Filter authors for J. Rapp or J. Nitschke
Fix #195
Test URLs:
- After: https://issue-195--zeiss--hlxsites.hlx.page/

Adjust press release authors

---

blocks/footer/footer.css
blocks/footer/footer.js
styles/simplified-styles.css

Fix #169 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020
- After: https://issue-169--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020

Issue-169 Footer changes wrt to small screen

---

blocks/cards/cards.css

Fixes: #114
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/drafts/satyam/demo
- After: https://issue-114--zeiss--hlxsites.hlx.page/drafts/satyam/demo

Ensure cards get equally sized

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js
test/blocks/carousel/carousel.plain.html
test/blocks/carousel/carousel.test.js

Fix #85 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/quality-supplier-award-2019-en-only
- After: https://issue-85--zeiss--hlxsites.hlx.live/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/quality-supplier-award-2019-en-only

issue-85 Simplified Carousel Block

---

blocks/footer/footer.js
styles/simplified-styles.css
styles/styles.css

Fix #212 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt
- After: https://issue-212--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt

issue-212 Accordion small screen change

---

blocks/article-list/article-list.css
blocks/article-list/article-list.js
styles/simplified-styles.css

Fixes #52
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/neue-multifunktionsfabrik-in-wetzlar
- After:  https://issue-52_sq--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/neue-multifunktionsfabrik-in-wetzlar

Simplify "Article Lists" block's markup

---

blocks/contact/contact.css
blocks/contact/contact.js
styles/simplified-styles.css
test/blocks/contact/authors/jeannine-rapp.plain.html
test/blocks/contact/contact.plain.html
test/blocks/contact/contact.test.js

Fix #49 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020
- After: https://issue-49--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020

issue-49 Contact Block simplified

---

blocks/footer/fallback_de.html
blocks/footer/fallback_en.html
blocks/footer/footer.js
blocks/header/fallback_de.html
blocks/header/fallback_en.html
blocks/header/header.js
blocks/press-cards/press-cards.js

Contributes towards #221
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/neue-multifunktionsfabrik-in-wetzlar
- After: https://issue-221_sq--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/neue-multifunktionsfabrik-in-wetzlar

User fallback headers and footers in case the original ones can't be fetched

---

tools/importer/import.js

Fixes #222
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/neue-multifunktionsfabrik-in-wetzlar
- After: https://issue-222--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/neue-multifunktionsfabrik-in-wetzlar

Remove the 'Number of Articles' property from the 'Article List' in the importer

---

blocks/header/header.js

Fix #223 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung-21-Apr-23-bkp/ausgezeichnete-ausbildung-bei-zeiss
- After: https://issue-223--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung-21-Apr-23-bkp/ausgezeichnete-ausbildung-bei-zeiss

issue-223 Icons/images missing in navbar

---

styles/styles.css

Fix #227 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020
- After: https://issue-227--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020

issue-227 Header fixes in Mozilla

---

blocks/cards/cards.css

Fix #215 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/drafts/piyush/demo
- After: https://issue-215--zeiss--hlxsites.hlx.page/drafts/piyush/demo

issue-215 Changes wrt to cards block

---

.github/pull_request_template.md

Fix #0000
Test URLs:
- After: https://update-pr-template--zeiss--hlxsites.hlx.page/

Fill default PR template with known coordinates

---

tools/importer/import.js

Fix #236 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/drafts/tmaret/issue-236/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/quality-supplier-award-2019
- After: https://issue-236--zeiss--hlxsites.hlx.page/drafts/tmaret/issue-236/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/quality-supplier-award-2019

issue-236 - Remove the GTM noscript tag from the body

---

tools/importer/import.js

Fix #239 
Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/drafts/tmaret/issue-239/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/zeiss-expandiert-am-forschungs-und-entwicklungsstandort-rossdorf
- After: https://issue-239--zeiss--hlxsites.hlx.page/drafts/tmaret/issue-239/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/zeiss-expandiert-am-forschungs-und-entwicklungsstandort-rossdorf

Skip empty collapsible tags

---

blocks/footer/footer.css
blocks/header/header.css
head.html
reference-styles.css
styles/images.css
styles/simplified-styles.css
styles/styles.css

Revert "Consolidate styles and eliminate unnecessary ones"
